name: Python CI

on: 
  push:
    branches: 
      - 'main'
      
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4 
        
      - name: Build Project
        run: echo "building the project...."
        
      - name: Set up Python
        uses: actions/setup-python@v5   # ✅ correct action
        with:
          python-version: '3.12'        # ✅ use stable version
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt   # ✅ check filename
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4 
        
      - name: Build Project
        run: echo "building the project...."
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          
      - name: Run tests
        run: pytest
