name: Print Commit Message

on: 
  push:
    branches: 
      - 'main'
      
jobs: 
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: actions/checkout@v5
        
      - name: Print message
        run: |
            echo "commit message:"
            git log -1 --pretty=%B
