name: Print Message

on: 
  push:
    branches: 
      - master
      
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4 
        
      - name: Build Project
        run: echo "building the project...."
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4 
        
      - name: Test Project
        run: echo "testing the project...."
         
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4 
        
      - name: Deploy Project
        run: echo "deploying the project...."
         